http:
  middlewares:
    middlewares-oauth:
      forwardAuth:
        address: http://oauth:4181
        trustForwardHeader: true
        authResponseHeaders: X-Forwarded-User
    oauth-chain:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-oauth
